export const user_data=[
    {'name': "maei",
    'lastName' : "karimi",
    'password' : 1234,
    'userName' : "maeikeyar",
    'email' : "maei@gmail.com",
    'gender' : "female"},
    {'name': "hana",
    'lastName' : "karimi",
    'password' : 4567,
    'userName' : "hanakeyar",
    'email' : "hana@gmail.com",
    'gender' : "female"},
    {'name': "mohammad",
    'lastName' : "karimi",
    'password' : 7890,
    'userName' : "mhkeyar",
    'email' : "mohammad@gmail.com",
    'gender' : "male"},
    {'name': "sara",
    'lastName' : "karimi",
    'password' : 0123,
    'userName' : "sarakeyar",
    'email' : "sara@gmail.com",
    'gender' : "female"},
    {'name': "reza",
    'lastName' : "karimi",
    'password' : 3456,
    'userName' : "rezakeyar",
    'email' : "reza@gmail.com",
    'gender' : "male"},
];